# Warning:
#
# If you configure a lot of the possible sensors etc. it could be that you run
# out of memory (on esp8266). If you configure nearly all sensors etc. you run
# in a stack-size issue. In this case you have to increase stack size!
#
#  https://github.com/esphome/issues/issues/855

substitutions:
  name: pipsolar
  external_components_source: github://syssi/esphome-pipsolar@pi18
  tx_pin: GPIO1
  rx_pin: GPIO3

esphome:
  name: ${name}

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:

logger:
  baud_rate: 0

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  id: mqtt_client

uart:
  - id: uart_0
    baud_rate: 2400
    tx_pin: ${tx_pin}
    rx_pin: ${rx_pin}
#    debug:
#      direction: BOTH
#      dummy_receiver: false
#      after:
#        delimiter: "\r"
#      sequence:
#        - lambda: UARTDebug::log_string(direction, bytes);

pipsolar:
  uart_id: uart_0
  id: inverter0

sensor:
  - platform: pipsolar
    pipsolar_id: inverter0
    # P007PIRI
    # Static Infos
    #grid_rating_voltage:
    #  name: "${name} AC input rated voltage"
    #grid_rating_current:
    #  name: "${name} AC input rated current"
    #ac_output_rating_voltage:
    #  name: "${name} AC output rated voltage"
    #ac_output_rating_frequency:
    #  name: "${name} AC output rated frequency"
    #ac_output_rating_current:
    #  name: "${name} AC output rated current"
    #ac_output_rating_apparent_power:
    #  name: "${name} ac_output_rating_apparent_power"
    #ac_output_rating_active_power:
    #  name: "${name} AC output rating active power"
    #battery_rating_voltage:
    #  name: "${name} Battery rated voltage"
    #parallel_max_num:
    #  name: "${name} Parallel max num"
    #mppt_string:
    #  name: "${name} MPPT string"
    #topology:
    #  name: "${name} Topology"
    #output_mode:
    #  name: "${name} Output mode setting"

    # Settable
    battery_recharge_voltage:
      name: "${name} Battery re-charge voltage"

    # Settable
    battery_redischarge_voltage:
      name: "${name} Battery re-discharge voltage"

    # Settable
    battery_under_voltage:
      name: "${name} Battery under voltage"

    # Settable
    battery_bulk_voltage:
      name: "${name} Battery bulk voltage"

    # Settable
    battery_float_voltage:
      name: "${name} Battery float voltage"

    # Settable
    battery_type:
      name: "${name} Battery type"

    # Settable
    current_max_ac_charging_current:
      name: "${name} Max AC charging current"

    # Settable
    current_max_charging_current:
      name: "${name} Max charging current"

    # Settable
    input_voltage_range:
      # Appliances 90-280V
      # UPS 170-280V
      name: "${name} Input voltage range"

    # P005GS
    grid_voltage:
      name: "${name} grid_voltage"
    grid_frequency:
      name: "${name} grid_frequency"
    ac_output_voltage:
      name: "${name} ac_output_voltage"
    ac_output_frequency:
      name: "${name} ac_output_frequency"
    ac_output_apparent_power:
      name: "${name} ac_output_apparent_power"
    ac_output_active_power:
      name: "${name} ac_output_active_power"
    output_load_percent:
      name: "${name} output_load_percent"
    battery_voltage:
      name: "${name} battery_voltage"
    # battery_voltage_scc:
    #   name: "${name} battery_voltage_scc"
    # battery_voltage_scc2:
    #   name: "${name} battery_voltage_scc2"
    battery_discharge_current:
      name: "${name} battery_discharge_current"
    battery_charging_current:
      name: "${name} battery_charging_current"
    battery_capacity_percent:
      name: "${name} battery_capacity_percent"
    inverter_heat_sink_temperature:
      name: "${name} inverter_heat_sink_temperature"
    # mppt1_charger_temperature:
    #   name: "${name} mppt1_charger_temperature"
    # mppt2_charger_temperature:
    #   name: "${name} mppt2_charger_temperature"
    pv1_input_power:
      name: "${name} pv1_input_power"
    # pv2_input_power:
    #   name: "${name} pv2_input_power"
    pv1_input_voltage:
      name: "${name} pv1_input_voltage"
    # pv2_input_voltage:
    #   name: "${name} pv2_input_voltage"
    mppt1_charger_status:
      name: "${name} mppt1_charger_status"
    # mppt2_charger_status:
    #   name: "${name} mppt2_charger_status"
    battery_power_direction:
      name: "${name} battery_power_direction"
    dc_ac_power_direction:
      name: "${name} dc_ac_power_direction"
    line_power_direction:
      name: "${name} line_power_direction"
    fault_code:
      name: "${name} wfs fault_code"
    local_parallel_id:
      name: "${name} local_parallel_id"

    # P007PGS0
    total_ac_output_apparent_power:
      name: "${name} total_ac_output_apparent_power"
    total_ac_output_active_power:
      name: "${name} total_ac_output_active_power"
    total_output_load_percent:
      name: "${name} total_output_load_percent"
    total_battery_charging_current:
      name: "${name} total_battery_charging_current"

    total_generated_energy:
      name: "${name} total_generated_energy"

binary_sensor:
  - platform: pipsolar
    pipsolar_id: inverter0
    # P007GS
    setting_value_configuration_state:
      name: "${name} setting_value_configuration_state"
    load_connection:
      name: "${name} load_connection"
    # # P007FLAG
    # silence_buzzer_open_buzzer:
    #   name: "${name} flag silence_buzzer_open_buzzer"
    # overload_bypass_function:
    #   name: "${name} flag overload_bypass_function"
    # lcd_escape_to_default:
    #   name: "${name} flag lcd_escape_to_default"
    # overload_restart_function:
    #   name: "${name} flag overload_restart_function"
    # over_temperature_restart_function:
    #   name: "${name} flag over_temperature_restart_function"
    # backlight_on:
    #   name: "${name} flag backlight_on"
    # alarm_on_when_primary_source_interrupt:
    #   name: "${name} flag alarm_on_when_primary_source_interrupt"
    # fault_code_record:
    #   name: "${name} flag fault_code_record"
    # power_saving:
    #   name: "${name} flag power_saving"
    # P005FWS
    warning_line_fail:
      name: "${name} wfs warning_line_fail"
    warning_output_circuit_short:
      name: "${name} wfs warning_output_circuit_short"
    warning_over_temperature:
      name: "${name} wfs warning_over_temperature"
    warning_fan_lock:
      name: "${name} wfs warning_fan_lock"
    warning_battery_voltage_high:
      name: "${name} wfs warning_battery_voltage_high"
    warning_battery_low_alarm:
      name: "${name} wfs warning_battery_low_alarm"
    warning_battery_under_shutdown:
      name: "${name} wfs warning_battery_under_shutdown"
    warning_over_load:
      name: "${name} wfs warning_over_load"
    warning_eeprom_failed:
      name: "${name} wfs warning_eeprom_failed"
    warning_power_limit:
      name: "${name} wfs warning_power_limit"
    warning_pv1_voltage_high:
      name: "${name} wfs warning_pv1_voltage_high"
    warning_pv2_voltage_high:
      name: "${name} wfs warning_pv2_voltage_high"
    warning_mppt1_overload:
      name: "${name} wfs warning_mppt1_overload"
    warning_mppt2_overload:
      name: "${name} wfs warning_mppt2_overload"
    scc1_battery_too_low_to_charge:
      name: "${name} wfs scc1_battery_too_low_to_charge"
    # scc2_battery_too_low_to_charge:
    #   name: "${name} wfs scc2_battery_too_low_to_charge"

text_sensor:
  - platform: pipsolar
    pipsolar_id: inverter0
    device_mode:
      name: "${name} Device mode"

switch:
  - platform: pipsolar
    pipsolar_id: inverter0
    silence_buzzer_open_buzzer:
      name: "${name} Buzzer beep"
    overload_bypass_function:
      name: "${name} Overload bypass function"
    lcd_escape_to_default:
      name: "${name} LCD escape to default Page"
    overload_restart_function:
      name: "${name} Overload restart"
    over_temperature_restart_function:
      name: "${name} Over temperature restart"
    backlight_on:
      name: "${name} Backlight"
    alarm_on_when_primary_source_interrupt:
      name: "${name} Alarm when primary source interrupt"
    fault_code_record:
      name: "${name} Fault code record"

select:
  - platform: pipsolar
    pipsolar_id: inverter0
    output_source_priority:
      id: inverter0_output_source_priority_select
      name: "${name} Output source priority" # P007PIRI
      optionsmap:
        "Solar-Utility-Battery": "POP0"
        "Solar-Battery-Utility": "POP1"
      statusmap:
        "0": "Solar Utility Battery"
        "1": "Solar Battery Utility"

  - platform: pipsolar
    pipsolar_id: inverter0
    charger_source_priority:
      id: inverter0_charger_source_priority_select
      name: "${name} Charger source priority" # P007PIRI
      optionsmap:
        "Solar first": "PCP0,0"
        "Solar and Utility": "PCP0,1"
        "Only solar": "PCP0,2"
      statusmap:
        "0": "Solar first"
        "1": "Solar and Utility"
        "2": "Only solar"

  - platform: pipsolar
    pipsolar_id: inverter0
    solar_power_priority:
      id: inverter0_solar_power_priority_select
      name: "${name} Solar power priority" # P007PIRI
      optionsmap:
        "Battery-Load-Utiliy": "PSP0"
        "Load-Battery-Utiliy": "PSP1"
      statusmap:
        "0": "Battery-Load-Utiliy"
        "1": "Load-Battery-Utiliy"
  - platform: pipsolar
    pipsolar_id: inverter0
    machine_type:
      id: inverter0_machine_type_select
      name: "${name} Machine type" # P007PIRI
      optionsmap:
        "OFF-Grid": "PDI"
        "Grid-Tie": "PEI"
      statusmap:
        "0": "OFF-Grid"
        "1": "Grid-Tie"
output:
  - platform: pipsolar
    pipsolar_id: inverter0
    current_max_ac_charging_current:
      id: inverter0_current_max_ac_charging_current
    current_max_charging_current:
      id: inverter0_current_max_charging_current
